'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useTheme } from 'next-themes';
import { Activity,AlertTriangle,CircleDollarSign,DatabaseZap,FileClock,LayoutDashboard,Moon,PackageSearch,ReceiptText,RotateCcw,Settings,ShoppingCart,Sun,TrendingUp } from 'lucide-react';
import { Button } from '@amazon-profit/ui';
import { cn } from '@amazon-profit/utils';
const links=[['/dashboard','Overview',LayoutDashboard],['/profit-loss','Profit & Loss',CircleDollarSign],['/sku-profitability','SKU Profitability',PackageSearch],['/ppc-analytics','PPC Analytics',TrendingUp],['/orders','Orders',ShoppingCart],['/refunds','Refunds',RotateCcw],['/cogs','COGS Manager',ReceiptText],['/connections','Amazon Connections',DatabaseZap],['/sync-history','Sync History',FileClock],['/alerts','Alerts',AlertTriangle],['/settings','Settings',Settings]] as const;
export function Shell({children}:{children:React.ReactNode}){const path=usePathname(),{theme,setTheme}=useTheme();return <div className="min-h-screen"><aside className="fixed inset-y-0 left-0 hidden w-64 border-r bg-card lg:flex lg:flex-col"><div className="flex h-16 items-center gap-3 border-b px-5"><div className="grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground"><Activity className="size-5"/></div><div><b>RealProfit OS</b><p className="text-xs text-muted-foreground">Amazon analytics</p></div></div><nav className="flex-1 space-y-1 p-3">{links.map(([href,label,Icon])=><Link key={href} href={href} className={cn('flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-muted-foreground hover:bg-muted hover:text-foreground',path===href&&'bg-primary/10 text-primary')}><Icon className="size-4"/>{label}</Link>)}</nav><div className="m-3 rounded-xl border bg-muted/50 p-4"><b className="text-sm">Northstar Brand</b><p className="text-xs text-muted-foreground">Amazon US · Mock connected</p></div></aside><div className="lg:pl-64"><header className="sticky top-0 z-20 flex h-16 items-center justify-end gap-2 border-b bg-background/90 px-4 backdrop-blur lg:px-8"><Button variant="outline">Last 30 days</Button><Button variant="ghost" size="icon" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun className="size-4"/>:<Moon className="size-4"/>}</Button><div className="grid size-9 place-items-center rounded-full bg-primary/15 font-semibold text-primary">MD</div></header><main className="p-4 lg:p-8">{children}</main></div></div>}
