import 'reflect-metadata';
import { ValidationPipe } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module.js';
const app=await NestFactory.create(AppModule,{bodyParser:false});
app.enableCors({origin:(process.env.TRUSTED_ORIGINS??'http://localhost:3000').split(','),credentials:true});
app.useGlobalPipes(new ValidationPipe({whitelist:true,transform:true}));
app.enableShutdownHooks();
await app.listen(Number(process.env.PORT??4000),'0.0.0.0');
console.log('[api] http://localhost:4000');
